# Generated by Django 4.2.16 on 2024-11-13 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('is_admin', models.BooleanField(default=0)),
                ('is_active', models.BooleanField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(blank=True, max_length=255, null=True)),
                ('option1', models.CharField(blank=True, max_length=255, null=True)),
                ('option2', models.CharField(blank=True, max_length=255, null=True)),
                ('option3', models.CharField(blank=True, max_length=255, null=True)),
                ('option4', models.CharField(blank=True, max_length=255, null=True)),
                ('correct_answer', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_response', models.CharField(blank=True, max_length=255, null=True)),
                ('marks', models.IntegerField(default=0)),
                ('question', models.ManyToManyField(db_column='question', related_name='user_response_question', to='quiz_app.questions')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='user_response_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='questions',
            index=models.Index(fields=['question'], name='quiz_app_qu_questio_6e1170_idx'),
        ),
        migrations.AddIndex(
            model_name='questions',
            index=models.Index(fields=['correct_answer'], name='quiz_app_qu_correct_a26659_idx'),
        ),
        migrations.AddIndex(
            model_name='userresponse',
            index=models.Index(fields=['user_response'], name='quiz_app_us_user_re_65b3f5_idx'),
        ),
        migrations.AddIndex(
            model_name='userresponse',
            index=models.Index(fields=['user'], name='quiz_app_us_user_d1db53_idx'),
        ),
    ]
