# Generated by Django 4.2.16 on 2024-11-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
